baseURL = "https://whoiszihan.github.io"
languageCode = "zh-CN"
title = "Eat, shop, drink, think."
theme = "beautifulhugo"

showArchiveCount = true

mathjax = true
mathjaxEnableSingleDollar = true
mathjaxEnableAutoNumber = false

# [taxonomies]
#   tag = "tags"

# 主导航菜单
name="首页"
url="/"
weight="1"
[[menu.main]]
  name="文章"
  url="/posts"
  weight="2"
[[menu.main]]
  name="分类"
  url="/tags"
  weight="3"
[[menu.main]]
  name="关于"
  url="/about"
  weight="4"
